parameters:
#    maastermedia_dojo.example.class: Maastermedia\DojoBundle\Example

services:
#    maastermedia_dojo.example:
#        class: %maastermedia_dojo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
