services:
    twig.extension.dojo:
        class: Dojo\DojoBundle\Twig\Extension\DojoExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension, alias: dojo }
