parameters:
#    dojo.example.class: Dojo\DojoBundle\Example

services:
#    dojo.example:
#        class: %maastermedia_dojo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
